/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */
package com.bigkoo.pickerview;

public final class R {
	public static final class anim {
		public static final int timepicker_anim_enter_bottom = 0x7f05001c;
		public static final int timepicker_anim_exit_bottom = 0x7f05001d;
	}
	public static final class color {
		public static final int wheel_timebtn_nor = 0x7f0d008d;
		public static final int wheel_timebtn_pre = 0x7f0d008e;
	}
	public static final class drawable {
		public static final int bg_above_timepicker = 0x7f020074;
		public static final int bg_line_timepicker = 0x7f020075;
		public static final int wheel_timebtn = 0x7f0201a8;
		public static final int wheel_val = 0x7f0201a9;
	}
	public static final class id {
		public static final int btnCancel = 0x7f0e01dd;
		public static final int btnSubmit = 0x7f0e01df;
		public static final int day = 0x7f0e01e2;
		public static final int hour = 0x7f0e01e3;
		public static final int min = 0x7f0e01e4;
		public static final int month = 0x7f0e01e1;
		public static final int options1 = 0x7f0e01da;
		public static final int options2 = 0x7f0e01db;
		public static final int options3 = 0x7f0e01dc;
		public static final int optionspicker = 0x7f0e02cb;
		public static final int timepicker = 0x7f0e02cc;
		public static final int year = 0x7f0e01e0;
	}
	public static final class layout {
		public static final int include_optionspicker = 0x7f040057;
		public static final int include_timepicker = 0x7f040059;
		public static final int pw_options = 0x7f040094;
		public static final int pw_time = 0x7f040095;
	}
	public static final class string {
		public static final int pickerview_cancel = 0x7f070085;
		public static final int pickerview_day = 0x7f070086;
		public static final int pickerview_hours = 0x7f070087;
		public static final int pickerview_minutes = 0x7f070088;
		public static final int pickerview_month = 0x7f070089;
		public static final int pickerview_seconds = 0x7f07008a;
		public static final int pickerview_submit = 0x7f07008b;
		public static final int pickerview_year = 0x7f07008c;
	}
	public static final class style {
		public static final int timepopwindow_anim_style = 0x7f0a0175;
	}
}
