/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */
package com.crazecoder.ui;

public final class R {
	public static final class anim {
		public static final int actionsheet_dialog_in = 0x7f05000a;
		public static final int actionsheet_dialog_out = 0x7f05000b;
		public static final int gear_spinner = 0x7f050016;
		public static final int round_spinner = 0x7f050017;
		public static final int round_spinner_apple = 0x7f050018;
		public static final int round_spinner_fade = 0x7f050019;
		public static final int slide_in_bottom = 0x7f05001a;
		public static final int slide_out_bottom = 0x7f05001b;
	}
	public static final class attr {
		public static final int colors = 0x7f0100ff;
		public static final int cornerRadius = 0x7f0100fe;
		public static final int direction = 0x7f010101;
		public static final int gaps = 0x7f010102;
		public static final int gravity = 0x7f010158;
		public static final int horizonGap = 0x7f010103;
		public static final int outerStrokeWidth = 0x7f010106;
		public static final int shadowSpace = 0x7f010107;
		public static final int texts = 0x7f010100;
		public static final int tintColor = 0x7f010105;
		public static final int verticalGap = 0x7f010104;
	}
	public static final class color {
		public static final int actionsheet_blue = 0x7f0d0006;
		public static final int actionsheet_gray = 0x7f0d0007;
		public static final int actionsheet_red = 0x7f0d0008;
		public static final int alertdialog_line = 0x7f0d0009;
		public static final int bgColor_overlay = 0x7f0d0010;
		public static final int black = 0x7f0d0011;
		public static final int pickerview_bg_topbar = 0x7f0d0058;
		public static final int pickerview_timebtn_nor = 0x7f0d0059;
		public static final int pickerview_timebtn_pre = 0x7f0d005a;
		public static final int pickerview_topbar_title = 0x7f0d005b;
		public static final int trans = 0x7f0d007b;
	}
	public static final class dimen {
		public static final int activity_horizontal_margin = 0x7f090019;
		public static final int activity_vertical_margin = 0x7f09004f;
		public static final int pickerview_topbar_btn_textsize = 0x7f09008a;
		public static final int pickerview_topbar_height = 0x7f09008b;
		public static final int pickerview_topbar_paddingleft = 0x7f09008c;
		public static final int pickerview_topbar_paddingright = 0x7f09008d;
		public static final int pickerview_topbar_title_textsize = 0x7f09008e;
	}
	public static final class drawable {
		public static final int actionsheet_bottom_normal = 0x7f02004b;
		public static final int actionsheet_bottom_pressed = 0x7f02004c;
		public static final int actionsheet_bottom_selector = 0x7f02004d;
		public static final int actionsheet_middle_normal = 0x7f02004e;
		public static final int actionsheet_middle_pressed = 0x7f02004f;
		public static final int actionsheet_middle_selector = 0x7f020050;
		public static final int actionsheet_single_normal = 0x7f020051;
		public static final int actionsheet_single_pressed = 0x7f020052;
		public static final int actionsheet_single_selector = 0x7f020053;
		public static final int actionsheet_top_normal = 0x7f020054;
		public static final int actionsheet_top_pressed = 0x7f020055;
		public static final int actionsheet_top_selector = 0x7f020056;
		public static final int alert_bg = 0x7f020057;
		public static final int alert_btn_left_pressed = 0x7f020058;
		public static final int alert_btn_right_pressed = 0x7f020059;
		public static final int alert_btn_single_pressed = 0x7f02005a;
		public static final int alertdialog_left_selector = 0x7f02005b;
		public static final int alertdialog_right_selector = 0x7f02005c;
		public static final int alertdialog_single_selector = 0x7f02005d;
		public static final int apple_round_spinner_00 = 0x7f02005e;
		public static final int apple_round_spinner_01 = 0x7f02005f;
		public static final int apple_round_spinner_02 = 0x7f020060;
		public static final int apple_round_spinner_03 = 0x7f020061;
		public static final int apple_round_spinner_04 = 0x7f020062;
		public static final int apple_round_spinner_05 = 0x7f020063;
		public static final int apple_round_spinner_06 = 0x7f020064;
		public static final int apple_round_spinner_07 = 0x7f020065;
		public static final int apple_round_spinner_08 = 0x7f020066;
		public static final int apple_round_spinner_09 = 0x7f020067;
		public static final int apple_round_spinner_10 = 0x7f020068;
		public static final int apple_round_spinner_11 = 0x7f020069;
		public static final int aq_10 = 0x7f02006a;
		public static final int aq_11 = 0x7f02006b;
		public static final int aq_12 = 0x7f02006c;
		public static final int aq_9 = 0x7f020071;
		public static final int dialog_background = 0x7f020097;
		public static final int failure = 0x7f020098;
		public static final int gear_spinner_00 = 0x7f020099;
		public static final int gear_spinner_01 = 0x7f02009a;
		public static final int gear_spinner_02 = 0x7f02009b;
		public static final int gear_spinner_03 = 0x7f02009c;
		public static final int gear_spinner_04 = 0x7f02009d;
		public static final int gear_spinner_05 = 0x7f02009e;
		public static final int gear_spinner_06 = 0x7f02009f;
		public static final int gear_spinner_07 = 0x7f0200a0;
		public static final int gear_spinner_08 = 0x7f0200a1;
		public static final int gear_spinner_09 = 0x7f0200a2;
		public static final int round_spinner_fade_00 = 0x7f0200e8;
		public static final int round_spinner_fade_01 = 0x7f0200e9;
		public static final int round_spinner_fade_02 = 0x7f0200ea;
		public static final int round_spinner_fade_03 = 0x7f0200eb;
		public static final int round_spinner_fade_04 = 0x7f0200ec;
		public static final int round_spinner_fade_05 = 0x7f0200ed;
		public static final int round_spinner_fade_06 = 0x7f0200ee;
		public static final int round_spinner_fade_07 = 0x7f0200ef;
		public static final int selector_pickerview_btn = 0x7f0200fb;
		public static final int shadow = 0x7f0200fc;
		public static final int spinner_round_00 = 0x7f020103;
		public static final int spinner_round_01 = 0x7f020104;
		public static final int spinner_round_02 = 0x7f020105;
		public static final int spinner_round_03 = 0x7f020106;
		public static final int spinner_round_04 = 0x7f020107;
		public static final int spinner_round_05 = 0x7f020108;
		public static final int spinner_round_06 = 0x7f020109;
		public static final int spinner_round_07 = 0x7f02010a;
		public static final int spinner_round_08 = 0x7f02010b;
		public static final int spinner_round_09 = 0x7f02010c;
		public static final int spinner_round_10 = 0x7f02010d;
		public static final int spinner_round_11 = 0x7f02010e;
		public static final int success = 0x7f02010f;
		public static final int trans_bg = 0x7f020119;
	}
	public static final class id {
		public static final int btnCancel = 0x7f0e01dd;
		public static final int btnSubmit = 0x7f0e01df;
		public static final int btn_neg = 0x7f0e0326;
		public static final int btn_pos = 0x7f0e0328;
		public static final int center = 0x7f0e003b;
		public static final int content_container = 0x7f0e01ea;
		public static final int day = 0x7f0e01e2;
		public static final int horizon = 0x7f0e0059;
		public static final int hour = 0x7f0e01e3;
		public static final int imageview_failure = 0x7f0e019d;
		public static final int imageview_progress_spinner = 0x7f0e019c;
		public static final int imageview_success = 0x7f0e019e;
		public static final int img_line = 0x7f0e0327;
		public static final int lLayout_bg = 0x7f0e0324;
		public static final int lLayout_content = 0x7f0e0322;
		public static final int left = 0x7f0e0040;
		public static final int min = 0x7f0e01e4;
		public static final int month = 0x7f0e01e1;
		public static final int options1 = 0x7f0e01da;
		public static final int options2 = 0x7f0e01db;
		public static final int options3 = 0x7f0e01dc;
		public static final int optionspicker = 0x7f0e02cb;
		public static final int outmost_container = 0x7f0e01e9;
		public static final int right = 0x7f0e0041;
		public static final int sLayout_content = 0x7f0e0321;
		public static final int textview_message = 0x7f0e019f;
		public static final int timepicker = 0x7f0e02cc;
		public static final int tvTitle = 0x7f0e01de;
		public static final int txt_cancel = 0x7f0e0323;
		public static final int txt_msg = 0x7f0e0325;
		public static final int txt_title = 0x7f0e0320;
		public static final int vertical = 0x7f0e005a;
		public static final int year = 0x7f0e01e0;
	}
	public static final class integer {
		public static final int animation_default_duration = 0x7f0b0004;
	}
	public static final class layout {
		public static final int dialog_progress = 0x7f04004f;
		public static final int include_pickerview_topbar = 0x7f040058;
		public static final int layout_basepickerview = 0x7f040060;
		public static final int pickerview_options = 0x7f040091;
		public static final int pickerview_time = 0x7f040092;
		public static final int view_actionsheet = 0x7f0400ae;
		public static final int view_alertdialog = 0x7f0400af;
	}
	public static final class string {
		public static final int app_name = 0x7f070032;
		public static final int pickerview_cancel = 0x7f070085;
		public static final int pickerview_day = 0x7f070086;
		public static final int pickerview_hours = 0x7f070087;
		public static final int pickerview_minutes = 0x7f070088;
		public static final int pickerview_month = 0x7f070089;
		public static final int pickerview_seconds = 0x7f07008a;
		public static final int pickerview_submit = 0x7f07008b;
		public static final int pickerview_year = 0x7f07008c;
	}
	public static final class style {
		public static final int ActionSheetDialogAnimation = 0x7f0a0089;
		public static final int ActionSheetDialogStyle = 0x7f0a008a;
		public static final int AlertDialogStyle = 0x7f0a008d;
		public static final int AppBaseTheme = 0x7f0a000c;
		public static final int AppTheme = 0x7f0a0091;
		public static final int DialogTheme = 0x7f0a00bf;
	}
	public static final class styleable {
		public static final int[] SegmentControl = { 0x01010095, 0x7f0100fe, 0x7f0100ff, 0x7f010100, 0x7f010101, 0x7f010102, 0x7f010103, 0x7f010104 };
		public static final int SegmentControl_android_textSize = 0;
		public static final int SegmentControl_colors = 2;
		public static final int SegmentControl_cornerRadius = 1;
		public static final int SegmentControl_direction = 4;
		public static final int SegmentControl_gaps = 5;
		public static final int SegmentControl_horizonGap = 6;
		public static final int SegmentControl_texts = 3;
		public static final int SegmentControl_verticalGap = 7;
		public static final int[] ShSwitchView = { 0x7f010105, 0x7f010106, 0x7f010107 };
		public static final int ShSwitchView_outerStrokeWidth = 1;
		public static final int ShSwitchView_shadowSpace = 2;
		public static final int ShSwitchView_tintColor = 0;
		public static final int[] wheelview = { 0x7f010158 };
		public static final int wheelview_gravity = 0;
	}
}
